name: Docker Compose Validation

on:
  push:
    branches:
      - main

jobs:
  validate-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Wait for services to be ready
        run: sleep 10

      - name: Show running containers
        run: docker compose ps

      - name: Show logs (opcional para debug)
        run: docker compose logs

      - name: Shutdown
        if: always()
        run: docker compose down

